# -*- coding: utf-8 -*-
"""Ask_ULAB Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyVCqXz8jkaE4QFsh1XoZx7GrIwGs6Tl
"""

#!apt-get install -y zstd
!pip install numpy langchain==0.1.20 langchain_core langchain-groq langchain-community chromadb sentence-transformers -q
#!curl -fsSL https://ollama.com/install.sh | sh
print("Done")

# Ollama pull model

import subprocess
import time

subprocess.Popen(["ollama", "serve"])
time.sleep(5)
print("Ollama server started!")

!ollama pull qwen2.5
print("Model ready!")

#Import Modules

import os
from pathlib import Path

try:
  from langchain_core.documents import Document
  from langchain_community.embeddings import HuggingFaceEmbeddings
  from langchain_community.vectorstores import Chroma
  from langchain.chains import RetrievalQA
  from langchain_groq import ChatGroq
  from langchain_community.chat_models import ChatOllama
  from langchain_core.prompts import PromptTemplate
  from langchain.chains import ConversationalRetrievalChain
  print("ALL Imports Successfully.")

except ImportError as e:
  print(f"Import error: {e}")

#Configurations

file_path = "/content/ULAB_Data.txt"
with open(file_path, "r", encoding="utf-8") as f:
  content = f.read()

Chroma_DB_Path = "/ulab_chroma_db_multilingual"

Embedding_Model = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"

#
LLM_Model = "llama-3.3-70b-versatile"

#LLM_Model = "qwen2.5"

Top_K_Result = 10

#
GROQ_API_KEY = "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"

print("Content : \n", content)

#Load documents

def load_documents(file_path):
    docs = []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if ':' in line and line.startswith('ULAB_'):
                doc_id, content = line.split(':', 1)
                docs.append(Document(
                    page_content=content.strip(),
                    metadata={'id': doc_id.strip(), 'line': line_num}
                ))
    print(f"Loaded {len(docs)} documents")
    return docs

documents = load_documents(file_path)

# Create embeddings and store in ChromaDB

def create_vector_store(docs, embed_model, db_path):
    print(f"Loading {embed_model}...")

    embeddings = HuggingFaceEmbeddings(
        model_name=embed_model,
        model_kwargs={"device": "cuda"},
        encode_kwargs={"normalize_embeddings": True}
    )

    if Path(db_path).exists():
        print(f"Loading existing DB from {db_path}")
        return Chroma(
            persist_directory=db_path,
            embedding_function=embeddings
        )

    print(f"Creating new DB with {len(docs)} documents...")
    db = Chroma.from_documents(
        documents=docs,
        embedding=embeddings,
        persist_directory=db_path
    )
    print(f"Ready! {db._collection.count()} documents stored")
    return db

vector_store = create_vector_store(
    docs=documents,
    embed_model=Embedding_Model,
    db_path=Chroma_DB_Path
)

if not vector_store:
    print("Failed to create vector store")

# Build RAG chain

def build_rag_chain(vector_store, llm_model, api_key, top_k=5): #api_key

    retriever = vector_store.as_retriever(
        search_type="similarity",
        search_kwargs={"k": top_k}
    )
    print(f"Retriever ready (top-{top_k})")

    standalone_template = """Given the chat history and a follow-up question,
rephrase the follow-up question to be a standalone question.

Chat History: {chat_history}
Follow Up: {question}
Standalone Question:"""

    standalone_prompt = PromptTemplate(
        input_variables=["chat_history", "question"],
        template=standalone_template
    )

    answer_template = """You are Ask ULAB, the friendly AI assistant for the University of Liberal Arts Bangladesh (ULAB).

STRICT RULES:
1. Answer ONLY using the context provided below.
2. NEVER guess or add information not in the context.
3. If the answer is NOT in the context, say exactly:
   "I don't have that specific information. Please contact ULAB at admissions@ulab.edu.bd or call 01714-161613."
4. Format answers clearly — use bullet points or numbered lists when listing multiple items.
5. At the end of EVERY answer, add ONE helpful follow-up suggestion like:
   "Would you like to know about [related topic]?"
6. Keep answers friendly, clear, and concise.

Context:
{context}

Question: {question}

Answer:"""

    answer_prompt = PromptTemplate(
        input_variables=["context", "question"],
        template=answer_template
    )

    ### LLM 1
    llm = ChatGroq(
        model=llm_model,
        api_key=api_key,
        temperature=0.1,
        max_tokens=1024,

    ### LLM 2
    #llm = ChatOllama(
        #model=llm_model,
        #temperature=0.1,
    )
    print(f"LLM ready: {llm_model}")

    # Chain
    chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=retriever,
        condense_question_prompt=standalone_prompt,
        combine_docs_chain_kwargs={"prompt": answer_prompt},
        return_source_documents=True,
        verbose=False
    )
    print("RAG chain ready!")
    return chain


# Build the chain
rag_chain = build_rag_chain(
    vector_store=vector_store,
    llm_model=LLM_Model,
    #
    api_key=GROQ_API_KEY,
    top_k=Top_K_Result
)

# Helper function to ask questions

chat_history = []

def ask(question, chain, show_sources=False):
    if not chain:
        return "Error: Chain not initialized"

    if not question.strip():
        return "Please enter a valid question"

    result = chain.invoke({
        "question": question,
        "chat_history": chat_history
    })

    answer = result.get("answer") or result.get("result") or "No answer returned."

    chat_history.append((question, answer))

    if show_sources and "source_documents" in result:
        print(f"\nQ: {question}")
        print(f"A: {answer}")
        print("\nSources:")
        for i, doc in enumerate(result["source_documents"], 1):
            doc_id = doc.metadata.get("id", "Unknown")
            print(f"  {i}. [{doc_id}] {doc.page_content[:80]}...")
    else:
        print(f"\nQ: {question}")
        print(f"A: {answer}")

    return answer


print("ask() ready — Usage: ask('your question', rag_chain)")

#Test with sample questions

if rag_chain:
    test_questions = [
        "What is the CSE tuition fee at ULAB?",
        "What scholarship can I get with GPA 5.0?",
        "Where is ULAB permanent campus?",
        "What clubs are available at ULAB?",
        "What is the capital of Bangladesh?"
    ]

    print("RUNNING TEST QUERIES")

    for question in test_questions:
        ask(question, rag_chain, show_sources=False)
        print("-" * 60)
else:
    print("RAG chain not ready. Please run previous cells first.")

!pip install gradio -q

import gradio as gr

print(gr.__version__)

gradio_history = []

def chat_with_ulab(message, history):
    global gradio_history

    if not message.strip():
        return "Please enter a valid question."

    try:
        result = rag_chain.invoke({
            "question": message,
            "chat_history": gradio_history
        })

        answer = result.get("answer") or result.get("result") or "No answer returned."

        # Save to memory
        gradio_history.append((message, answer))

        return answer

    except Exception as e:
        return f"Error: {str(e)}"


# Gradio UI
demo = gr.ChatInterface(
    fn=chat_with_ulab,
    title="Ask ULAB",
    description="The Chat Bot for University of Liberal Arts Bangladesh",
    examples=[
        "What is the CSE tuition fee?",
        "What scholarship can I get with GPA 5.0?",
        "How many departments does ULAB have?",
        "Where is ULAB permanent campus?",
        "What clubs are available at ULAB?"
    ]
)

demo.launch(share=True, debug=False)